'01_BSOD':
    'PATH': 'C:\Windows'

'02_performance':
    'Intel':
      'PATH': 'C:\XXXX'
    'AMD':
      'PATH': 'C:\XXXX'
    'GPU':
      'PATH': 'C:\XXXX'
    'performance':
      'PATH': 'C:\XXXX'


'04_异常关机重启':
    'PATH': 'D:\0_shutdown_parse\test_data\01_异常关机重启_log\ALADDIN'

'04_异常唤不醒':
    'PATH': 'D:\0_shutdown_parse\test_data\01_异常关机重启_log\ALADDIN'


'05_SW_Hung':
    'PATH': 'C:\Windows'

'06_HW Hung':
    'PATH': 'C:\XXXX'

'06_HW Hung':
    'PATH': 'C:\XXXX'