'01_BSOD':
    'PATH': 'C:\Windows'

'02_performance':
    'Intel':
      'PATH': 'C:\XXXX'
    'AMD':
      'PATH': 'C:\XXXX'
    'GPU':
      'PATH': 'C:\XXXX'
    'performance':
      'PATH': 'C:\XXXX'


'04_异常关机重启':
    'PATH': 'D:\01_异常关机\01_ALADDIN_ILL-SVT-MSF5091023B-PF5XXDFZ-IDLEPHASE-ABNORMAL_SHUTDOWN_144BAFB6'

'04_异常唤不醒':
    'PATH': 'D:\03_睡眠休眠异常\S3 abnoamal resume'


'05_SW_Hung':
    'PATH': 'C:\Windows'

'06_HW Hung':
    'PATH': 'C:\XXXX'

'06_HW Hung':
    'PATH': 'C:\XXXX'