'0x00':
  root_casue: Reserved
  原因: 预订的
'0x01':
  root_casue: Shutdown ID for SB SLP_S5 signal
  原因: SB SLP_S5 信号的关闭 ID
'0x03':
  root_casue: APU thermal trip
  原因: APU热跳闸
'0x04':
  root_casue: Shutdown ID for command C:0x59 D:0xA2
  原因: 命令的关闭 ID C:0x59 D:0xA2
'0x05':
  root_casue: Shutdown ID for flash
  原因: 闪光灯关闭 ID
'0x06':
  root_casue: Shutdown ID for EC power reset
  原因: EC 电源重置的关闭 ID
'0x08':
  root_casue: Shutdown ID for boot fail restart by command C:0x40 D:0xXX
  原因: 通过命令 C:0x40 D:0xXX 启动失败重启的关闭 ID
'0x0A':
  root_casue: Shutdown ID for battery over temp
  原因: 电池温度过高的关机 ID
'0x0B':
  root_casue: Shutdown ID for thermal sensor communication fail
  原因: 热传感器通信失败的关闭 ID
'0x0C':
  root_casue: Shutdown ID for battery empty
  原因: 电池电量耗尽的关机 ID
'0x0E':
  root_casue: Shutdown ID for battery communication fail
  原因: 电池通信失败的关机ID
'0x0F':
  root_casue: Shutdown ID for battery abnormal device ID
  原因: 电池异常关机ID 设备ID
'0x11':
  root_casue: Shutdown ID for DTS over temp
  原因: DTS 过温关闭 ID
'0x12':
  root_casue: Shutdown ID for VGA thermal sensor over temp
  原因: VGA 热传感器过热关闭 ID
'0x13':
  root_casue: Shutdown ID for battery low voltage
  原因: 电池低电压关机ID
'0x1C':
  root_casue: Shutdown ID for External VGA thermal sensor over temp
  原因: 外部 VGA 热传感器过热关闭 ID
'0x20':
  root_casue: Shutdown ID VGA thermal  communication fail
  原因: 关机 ID VGA 热通讯失败
'0x21':
  root_casue: Shutdown ID External VGA thermal sensor communication fail
  原因: 关机 ID 外部 VGA 热传感器通信失败
'0x22':
  root_casue: Shutdown ID CPU thermal communication fail
  原因: 关机 ID CPU 热通讯失败
'0x23':
  root_casue: W114 Shutdown 4s
  原因: W114 关机 4 秒
'0x2A':
  root_casue: Shutdown ID for thermal sensor 1 communication fail
  原因: 热传感器关闭 ID 1 通信失败
'0x2B':
  root_casue: Shutdown ID for thermal sensor 2 communication fail
  原因: 热传感器 2 通信失败的关机 ID
'0x2C':
  root_casue: Shutdown ID for thermal sensor 3 communication fail
  原因: 热传感器 3 通信失败的关机 ID
'0x2D':
  root_casue: Shutdown ID for thermal sensor 4 communication fail
  原因: 热传感器 4 通信失败的关机 ID
'0x2E':
  root_casue: Shutdown ID for thermal sensor 5 communication fail
  原因: 热传感器关闭 ID 5 通信失败
'0x2F':
  root_casue: Shutdown ID for thermal sensor 6 communication fail
  原因: 热传感器 6 通信失败的关机 ID
'0x30':
  root_casue: Shutdown ID thermal sensor local over temp
  原因: 关闭 ID 热传感器局部过温
'0x31':
  root_casue: Shutdown ID thermal sensor remote over temp
  原因: 远程 ID 热传感器温度过高关闭
'0x32':
  root_casue: Shutdown ID thermal sensor remote over temp
  原因: 远程 ID 热传感器温度过高关闭
'0x33':
  root_casue: Shutdown ID CPU thermistor over temp
  原因: 关机 ID CPU 热敏电阻温度过高
'0x34':
  root_casue: Shutdown ID GPU thermistor over temp
  原因: 关闭 ID GPU 热敏电阻温度过高
'0x35':
  root_casue: ''
  原因: ''
'0x3A':
  root_casue: ''
  原因: null
'0x3B':
  root_casue: ''
  原因: ''
'0x40':
  root_casue: Force system shutdown with 5S when RSOC drop to 0%.
  原因: 当 RSOC 降至 0% 时，强制系统关闭 5 秒。
'0x41':
  root_casue: ''
  原因: ''
'0x59':
  root_casue: ''
  原因: ''
'0x70':
  root_casue: BIOS BSH WDT
  原因: BIOS BSH 看门狗定时器
'0xA0':
  root_casue: Shipmode battery communication fail
  原因: 船舶模式电池通信失败
'0xA1':
  root_casue: Shipmode battery communication fail
  原因: 船舶模式电池通信失败
'0xA2':
  root_casue: Shipmode battery communication fail
  原因: 船舶模式电池通信失败
'0xA3':
  root_casue: Shipmode battery communication fail
  原因: 船舶模式电池通信失败
'0xA6':
  root_casue: Shipmode pass 1
  原因: 船舶模式通行证 1
'0xA7':
  root_casue: Shipmode pass 2
  原因: 船舶模式通行证 2
'0xA8':
  root_casue: Shipmode pass 3
  原因: 船舶模式通行证 3
'0xA9':
  root_casue: Shipmode pass 4
  原因: 船舶模式通行证 4
'0xB0':
  root_casue: PD shutdownID 1
  原因: PD 关闭 ID 1
'0xB1':
  root_casue: PD shutdownID 2
  原因: PD 关闭ID 2
'0xB2':
  root_casue: PD shutdownID 3
  原因: PD 关闭 ID 3
'0xB4':
  root_casue: PD shutdownID 4
  原因: PD 关闭 ID 4
'0xBA':
  root_casue: Test WDT
  原因: 测试看门狗定时器
'0xBB':
  root_casue: Test WDT
  原因: 测试看门狗定时器
'0xBC':
  root_casue: Test WDT
  原因: 测试看门狗定时器
'0xBD':
  root_casue: Test WDT
  原因: 测试看门狗定时器
'0xBE':
  root_casue: Test WDT
  原因: 测试看门狗定时器
'0xBF':
  root_casue: Test WDT
  原因: 测试看门狗定时器
'0xC0':
  root_casue: WA shutdown ID    AMD memory traing hang up when BIOS is not live.
  原因: WA 关闭 ID 当 BIOS 不活动时 AMD 内存训练挂起。
'0xC1':
  root_casue: WA shutdown ID
  原因: WA 关闭 ID
'0xC2':
  root_casue: WA shutdown ID
  原因: WA 关闭 ID
'0xC3':
  root_casue: WA shutdown ID
  原因: WA 关闭 ID
'0xC4':
  root_casue: WA shutdown ID
  原因: WA 关闭 ID
'0xC5':
  root_casue: WA shutdown ID
  原因: WA 关闭 ID
'0xC6':
  root_casue: WA shutdown ID
  原因: WA 关闭 ID
'0xC7':
  root_casue: WA shutdown ID
  原因: WA 关闭 ID
'0xD8':
  root_casue: reserved shutdown ID 0xC8
  原因: 保留关闭ID 0xC8
'0xD9':
  root_casue: reserved shutdown ID 0xC9
  原因: 保留关闭ID 0xC9
'0xDA':
  root_casue: reserved shutdown ID 0xCA
  原因: 保留关闭ID 0xCA
'0xDB':
  root_casue: reserved shutdown ID 0xCB
  原因: 保留关闭ID 0xCB
'0xDC':
  root_casue: reserved shutdown ID 0xCC
  原因: 保留关闭ID 0xCC
'0xDD':
  root_casue: reserved shutdown ID 0xCD
  原因: 保留关闭ID 0xCD
'0xDE':
  root_casue: reserved shutdown ID 0xCE
  原因: 保留关闭ID 0xCE
'0xDF':
  root_casue: reserved shutdown ID 0xCF
  原因: 保留关闭ID 0xCF
'0xEC':
  root_casue: EC code reset
  原因: EC代码重置
'0xFF':
  root_casue: external watch-dog
  原因: 外部看门狗
'0xFE':
  root_casue: internal watch-dog
  原因: 内部看门狗
'0xFC':
  root_casue: EC VSTBY or WRST reset
  原因: EC VSTBY 或 WRST 复位
'0xFD':
  root_casue: 8S reset
  原因: 8秒复位
'0xFB':
  root_casue: Fn+D+H HW hang shutdown id
  原因: Fn+D+H 硬件挂起关机 ID
